abi = 5

# Infered properties:
# [[ruleset]]
# handled_access_fs = ["abi.all"]
# handled_access_net = ["bind_tcp"]
#
# We need to be careful to cover all access rights (e.g. abi.read_execute +
# abi.read_write = abi.all), otherwise the missing accesses would not be denied.

# Main system directories can be red.
[[path_beneath]]
allowed_access = ["abi.read_execute"]
parent = [".", "/bin", "/lib", "/usr", "/dev", "/etc", "/proc",]

# Only allow writing to /tmp.
[[path_beneath]]
allowed_access = ["abi.read_write"]
parent = ["/tmp"]
