[[variable]]
name = "tmp"
literal = ["/tmp", "/var/tmp"]

[[variable]]
name = "home"
literal = ["/root", "/home"]

[[variable]]
name = "config"
literal = ["/etc"]

# Main system file hierarchies can be read and executed.
[[path_beneath]]
allowed_access = ["v5.read_execute"]
parent = ["/bin", "/lib", "/usr", "/dev", "/proc", "${config}"]

# Only allow writing to temporary and home directories.
[[path_beneath]]
allowed_access = ["v5.read_write"]
parent = ["${tmp}", "${home}"]
