/* SPDX-License-Identifier: Apache-2.0 OR MIT */
/* Auto-generated by cbindgen. */

#ifndef LANDLOCKCONFIG_H
#define LANDLOCKCONFIG_H

struct landlockconfig;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Parses a JSON configuration file
 *
 * # Returns
 *
 * * Pointer to a landlockconfig object on success. This object must be freed
 *   with landlockconfig_free().
 * * -1 on error, and errno set to the error code.
 */
struct landlockconfig *landlockconfig_parse_json(int config_fd);

/**
 * Parses a TOML configuration file
 *
 * # Returns
 *
 * * Pointer to a landlockconfig object on success. This object must be freed
 *   with landlockconfig_free().
 * * -1 on error, and errno set to the error code.
 */
struct landlockconfig *landlockconfig_parse_toml(int config_fd);

/**
 * Frees a landlockconfig object
 *
 * # Safety
 *
 * The pointer must have been returned by landlockconfig_parse_json() or
 * landlockconfig_parse_toml().
 */
void landlockconfig_free(struct landlockconfig *config);

/**
 * Creates a ruleset from a landlockconfig object
 *
 * # Safety
 *
 * The pointer must have been returned by landlockconfig_parse_json() or
 * landlockconfig_parse_toml().
 *
 * # Returns
 *
 * * The ruleset file descriptor on success.
 * * -1 on error, and errno set to the error code.
 */
int landlockconfig_build_ruleset(const struct landlockconfig *config);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* LANDLOCKCONFIG_H */
